# Generated by Django 3.2.6 on 2021-09-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_project_manager',
            field=models.BooleanField(default=False),
        ),
    ]
