# Generated by Django 3.2.6 on 2021-09-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField()),
                ('actual_end_date', models.DateField()),
                ('estimated_hours', models.CharField(max_length=45)),
                ('actual_hours', models.CharField(max_length=45)),
                ('estimated_budget', models.CharField(max_length=45)),
                ('actual_budget', models.CharField(max_length=45)),
                ('is_adhoc', models.BooleanField()),
                ('client_partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.clientpartner')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
