# Generated by Django 3.2.6 on 2021-09-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=45)),
                ('cp_address', models.CharField(max_length=45)),
                ('cp_details', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='OnProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_partner', models.BooleanField()),
                ('is_client', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField()),
                ('actual_end_date', models.DateField()),
                ('estimated_hours', models.CharField(max_length=45)),
                ('actual_hours', models.CharField(max_length=45)),
                ('estimated_budget', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('project_no', models.CharField(max_length=45)),
                ('projectcol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
