# Generated by Django 3.2.6 on 2021-09-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_budget',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
